# Prueba United Way

Realizaré los códigos en Python.

In [18]:
import pandas as pd
import numpy as np
import plotly.express as px

## cargar los datos

In [19]:
url = "/content/PruebaExcel.xlsx"
Prueba = pd.read_excel(url, sheet_name=1)
Prueba.head()

,Código Dane,Institución,Identificación estudiante,Grado,Curso,MATEMÁTICAS,CIENCIAS SOCIALES,CIENCIAS NATURALES,LENGUAJE,COMUNICACIÓN,...,COMUNICATIVA ESCRITORA,ALEATORIO,NUMÉRICO - VARIACIONAL,GEOMÉTRICO - MÉTRICO,"CIENCIA, TECNOLOGÍA Y SOCIEDAD",ENTORNO VIVO,ENTORNO FÍSICO,SINTÁCTICO,SEMÁNTICO,PRAGMÁTICO
0,108001000433,IED VILLANUEVA SD PPAL,1,5,5-A,2.33,3.67,2.33,3.33,3,...,3.57,2,2.50,2.50,2,2,3,5.0,0,3.75
1,108001000433,IED VILLANUEVA SD PPAL,2,5,5-A,3.00,3.33,2.33,2.67,4,...,2.86,4,3.33,1.67,2,2,3,0.0,0,1.25
2,108001000433,IED VILLANUEVA SD PPAL,3,5,5-A,3.00,3.33,2.33,3.00,4,...,2.86,4,2.50,1.67,2,2,3,0.0,0,2.50
3,108001000433,IED VILLANUEVA SD PPAL,4,5,5-A,3.00,3.33,2.33,2.67,4,...,2.86,4,3.33,2.50,2,2,3,0.0,0,1.25
4,108001000433,IED VILLANUEVA SD PPAL,5,5,5-B,3.00,2.00,2.00,2.67,3,...,2.14,5,2.50,1.67,2,2,2,5.0,5,1.25

## Paso 1

1. Hacer una gráfica con los colegios que tengan un promedio por encima de 3.2 en la competencia de resolución de problemas.

_Debemos primero obtener el promedio por colegio_

In [27]:
Medias = Prueba.groupby("Institución", as_index=False).mean()
Medias[Medias['RESOLUCIÓN DE PROBLEMAS']>3.2]

Empty DataFrame
Columns: [Institución, Código Dane, Identificación estudiante, Grado, MATEMÁTICAS, CIENCIAS SOCIALES, CIENCIAS NATURALES, LENGUAJE, COMUNICACIÓN, RESOLUCIÓN DE PROBLEMAS, RAZONAMIENTO, PENSAMIENTO SOCIAL, PENSAMIENTO REFLEXIVO Y SISTÉMICO, INTERPRETACIÓN Y ANÁLISIS DE PERSPECTIVAS, INDAGACIÓN, USO COMPRENSIVO DEL CONOCIMIENTO CIENTÍFICO, EXPLICACIÓN DE FENÓMENOS, COMUNICATIVA LECTORA, COMUNICATIVA ESCRITORA, ALEATORIO, NUMÉRICO - VARIACIONAL, GEOMÉTRICO - MÉTRICO, CIENCIA, TECNOLOGÍA Y SOCIEDAD, ENTORNO VIVO, ENTORNO FÍSICO, SINTÁCTICO, SEMÁNTICO, PRAGMÁTICO]
Index: []

[0 rows x 28 columns]

No existe un colegio con media por encima de 3.2 en resolución de problemas. El valor máximo del promedio del colegio es 3.053

In [30]:
Medias[["Institución", 'RESOLUCIÓN DE PROBLEMAS']].describe()

       RESOLUCIÓN DE PROBLEMAS
count                20.000000
mean                  2.415622
std                   0.549778
min                   0.993197
25%                   2.369480
50%                   2.562088
75%                   2.737528
max                   3.053763

## Paso 2

2. Hacer una tabla dinámica agrupando por curso los resultados por área.

In [35]:
Prueba.groupby("Grado").count()

,Código Dane,Institución,Identificación estudiante,Curso,MATEMÁTICAS,CIENCIAS SOCIALES,CIENCIAS NATURALES,LENGUAJE,COMUNICACIÓN,RESOLUCIÓN DE PROBLEMAS,...,COMUNICATIVA ESCRITORA,ALEATORIO,NUMÉRICO - VARIACIONAL,GEOMÉTRICO - MÉTRICO,"CIENCIA, TECNOLOGÍA Y SOCIEDAD",ENTORNO VIVO,ENTORNO FÍSICO,SINTÁCTICO,SEMÁNTICO,PRAGMÁTICO
Grado,,,,,,,,,,,,,,,,,,,,,
5,1574,1574,1574,1574,1574,1574,1574,1574,1574,1574,...,1574,1574,1574,1574,1574,1574,1574,1574,1574,1574

Cómo todos son de grado 5, sólo se agrupa por curso e institución. Calculamos la media dentro de cada curso e institución

In [38]:
Medias_curso = Prueba[['Institución',  'Curso', 'MATEMÁTICAS', 
                       'CIENCIAS SOCIALES', 'CIENCIAS NATURALES',
       'LENGUAJE']].groupby(["Institución", "Curso"], as_index=False).mean()
Medias_curso

,Institución,Curso,MATEMÁTICAS,CIENCIAS SOCIALES,CIENCIAS NATURALES,LENGUAJE
0,IECD MANUEL ELKIN PATARROYO,5-A,2.716809,2.886383,2.623830,3.042553
1,IECD MANUEL ELKIN PATARROYO,5-B,2.390000,2.672453,2.496038,2.874906
2,IECD MANUEL ELKIN PATARROYO,5-C,2.527917,2.514583,2.443750,2.819583
3,IED BOSTON - SD PPAL,5-1,2.840789,2.894474,2.684737,2.973947
4,IED DE CARRIZAL - PPAL,5-A,2.968636,3.636818,2.954091,3.515455
5,IED DE CARRIZAL - PPAL,5-B,2.754211,3.158421,2.508947,3.526842
6,IED DE CARRIZAL - PPAL,5-C,2.940435,4.144348,3.434783,3.928696
7,IED DSLLO DEL TALENTO HUMANO,5-1,3.244000,3.233667,2.855333,3.344000
8,IED DSLLO DEL TALENTO HUMANO,5-2,2.988519,2.962593,2.691481,3.111852
9,IED DSLLO DEL TALENTO HUMANO,5-3,2.833929,3.001429,2.488214,3.345357
10,IED DSLLO DEL TALENTO HUMANO,5-A,2.330000,1.330000,1.670000,2.670000
11,IED ETNOEDU PAULINO SALGADO BATATA,5-1,2.603810,2.397619,2.381905,2.952381
12,IED ETNOEDU PAULINO SALGADO BATATA,5-2,2.534000,3.288667,2.467333,3.090000
13,IED GOLDA MEIR - SEDE PPAL,5-A,1.490000,1.544667,1.799667,1.955667
14,IED GOLDA MEIR - SEDE PPAL,5-B,1.523214,1.119286,1.095000,1.772500
15,IED JOSE CONSUEGRA HIGGINS,5-1,3.136364,2.773182,2.636818,3.243182
16,IED JOSE CONSUEGRA HIGGINS,5-2,2.848182,2.789091,2.332727,2.818182
17,IED JOSE CONSUEGRA HIGGINS,5-3,2.541875,2.875625,2.478750,3.021250
18,IED JOSE CONSUEGRA HIGGINS,5-4,2.142857,2.460000,2.349524,2.810000
19,IED JUAN JOSE RONDON - SEDE PPAL,5-1,3.364091,3.287727,3.121364,3.590000
20,IED JUAN JOSE RONDON - SEDE PPAL,5-2,2.798500,2.599500,2.349500,2.883500
21,IED LOS LAURELES,5-A,2.943143,2.571143,2.733143,3.199143
22,IED LOS LAURELES,5-B,2.476286,2.457714,2.303714,3.019143
23,IED LUIS CARLOS GALAN SARMIENTO,5-A,2.466176,2.367794,2.372206,2.750147
24,IED LUIS CARLOS GALAN SARMIENTO,5-B,2.436429,2.539762,2.523333,2.722381
25,IED LUIS CARLOS GALAN SARMIENTO,5-C,2.598667,2.600667,2.222000,2.754667
26,IED MUNDO BOLIVARIANO - SEDE PPAL,5-1,2.857619,2.842381,2.873333,3.254286
27,IED MUNDO BOLIVARIANO - SEDE PPAL,5-2,2.920952,2.856667,2.206190,2.778571
28,IED MUNDO BOLIVARIANO - SEDE PPAL,5-3,2.752963,2.704444,2.455926,3.036296
29,IED MUNDO BOLIVARIANO - SEDE PPAL,5-4,2.594286,2.642857,2.952857,2.713571
30,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-A,2.216000,2.451000,2.499500,2.833500
31,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-B,2.455455,2.969545,2.530909,3.061364
32,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-C,2.947895,3.333684,3.209474,3.262105
33,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-A,2.304348,2.376957,2.275217,2.465217
34,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-B,2.803182,2.787727,3.075909,3.378636
35,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-C,2.754737,2.648947,2.632105,2.998947
36,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-D,2.826296,2.962963,2.900741,3.307407
37,IED SALVADOR ENTREGAS - SEDE PPAL,5-1,2.868788,3.090606,2.413939,3.111212
38,IED SALVADOR ENTREGAS - SEDE PPAL,5-2,3.062973,2.648649,2.567838,2.937027
39,IED SAN SALVADOR,5-1,2.721875,3.055208,2.562708,3.041667
40,IED SANTA MARIA - SD PPAL,5-A,1.474697,1.328939,1.263182,1.555455
41,IED SANTA MARIA - SD PPAL,5-B,1.333443,1.398689,1.333279,1.639836
42,IED SANTA MARIA - SD PPAL,5-C,1.384000,1.200500,1.434000,1.532500
43,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-1,3.071071,3.214286,2.976429,3.369286
44,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-2,3.193158,3.156316,3.211053,3.350000
45,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-3,3.182273,3.317727,2.940000,3.621364
46,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-4,2.777917,2.542083,2.167500,2.917917
47,IED VILLANUEVA SD PPAL,5-A,2.610833,2.165833,1.360000,2.500000
48,IED VILLANUEVA SD PPAL,5-B,2.208750,1.458125,1.521875,1.979375
49,IED VILLAS DE SAN PABLO - SEDE PPAL,5-1,3.052895,2.815263,2.640263,3.035263
50,IED VILLAS DE SAN PABLO - SEDE PPAL,5-2,2.574828,2.620690,2.552069,2.712069
51,IED VILLAS DE SAN PABLO - SEDE PPAL,5-3,2.500000,2.520294,2.265000,2.891471
52,IED VILLAS DE SAN PABLO - SEDE PPAL,5-4,2.373333,2.473939,2.282424,2.676364
53,IED VILLAS DE SAN PABLO - SEDE PPAL,5-5,2.771562,2.864063,2.563438,3.270938
54,IED VILLAS DE SAN PABLO - SEDE PPAL,5-6,2.891935,2.827742,2.505806,3.096774
55,IIED EL CORAZON DEL SANTUARIO,5-1,2.499583,2.722083,2.402917,3.375417
56,IIED EL CORAZON DEL SANTUARIO,5-2,2.736316,2.596842,2.456316,2.718947

Para saber los mejores resultados por area, usaré el promedio de los estudiantes como guía.

In [43]:
Medias_curso.sort_values(by="MATEMÁTICAS", ascending=False)
## En matematicas es la IED JUAN JOSE RONDON

,Código Dane,Institución,Identificación estudiante,Grado,Curso,MATEMÁTICAS,CIENCIAS SOCIALES,CIENCIAS NATURALES,LENGUAJE,COMUNICACIÓN,...,COMUNICATIVA ESCRITORA,ALEATORIO,NUMÉRICO - VARIACIONAL,GEOMÉTRICO - MÉTRICO,"CIENCIA, TECNOLOGÍA Y SOCIEDAD",ENTORNO VIVO,ENTORNO FÍSICO,SINTÁCTICO,SEMÁNTICO,PRAGMÁTICO
1027,108001075476,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,1028,5,5-3,5.0,3.33,2.33,3.67,5,...,2.14,5,5.0,5.0,4,3,0,5.0,5,0.00
1073,108001075476,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,1074,5,5-4,5.0,2.00,0.67,2.67,5,...,2.14,5,5.0,5.0,2,0,0,5.0,0,2.50
548,108001004684,IED JOSE CONSUEGRA HIGGINS,549,5,5-1,5.0,2.33,3.33,4.00,5,...,2.86,5,5.0,5.0,3,4,3,5.0,5,3.75
1236,108001800065,IED VILLAS DE SAN PABLO - SEDE PPAL,1237,5,5-1,5.0,4.67,4.33,4.33,5,...,3.57,5,5.0,5.0,4,5,4,5.0,5,2.50
1005,108001075476,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,1006,5,5-2,5.0,4.33,4.00,4.00,5,...,4.29,5,5.0,5.0,4,5,3,0.0,0,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,108001002924,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,180,5,5-B,0.0,0.33,1.33,2.33,0,...,2.86,0,0.0,0.0,1,1,2,0.0,0,3.75
634,108001005516,IIED EL CORAZON DEL SANTUARIO,635,5,5-1,0.0,1.00,1.33,2.33,0,...,3.57,0,0.0,0.0,2,0,2,0.0,5,2.50
1425,108001800065,IED VILLAS DE SAN PABLO - SEDE PPAL,1426,5,5-4,0.0,0.33,2.67,1.33,0,...,1.43,0,0.0,0.0,2,3,3,0.0,0,2.50
1235,108001078998,IED SANTA MARIA - SD PPAL,1236,5,5-C,0.0,0.00,0.33,0.00,0,...,0.00,0,0.0,0.0,0,1,0,0.0,0,0.00
871,108001074534,IED LUIS CARLOS GALAN SARMIENTO,872,5,5-A,0.0,1.33,2.33,0.67,0,...,0.71,0,0.0,0.0,4,2,1,0.0,0,0.00

In [42]:
Medias_curso.sort_values(by="CIENCIAS SOCIALES", ascending=False)
## En ciencias sociales es la IED DE CARRIZAL

,Institución,Curso,MATEMÁTICAS,CIENCIAS SOCIALES,CIENCIAS NATURALES,LENGUAJE
6,IED DE CARRIZAL - PPAL,5-C,2.940435,4.144348,3.434783,3.928696
4,IED DE CARRIZAL - PPAL,5-A,2.968636,3.636818,2.954091,3.515455
32,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-C,2.947895,3.333684,3.209474,3.262105
45,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-3,3.182273,3.317727,2.940000,3.621364
12,IED ETNOEDU PAULINO SALGADO BATATA,5-2,2.534000,3.288667,2.467333,3.090000
19,IED JUAN JOSE RONDON - SEDE PPAL,5-1,3.364091,3.287727,3.121364,3.590000
7,IED DSLLO DEL TALENTO HUMANO,5-1,3.244000,3.233667,2.855333,3.344000
43,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-1,3.071071,3.214286,2.976429,3.369286
5,IED DE CARRIZAL - PPAL,5-B,2.754211,3.158421,2.508947,3.526842
44,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-2,3.193158,3.156316,3.211053,3.350000
37,IED SALVADOR ENTREGAS - SEDE PPAL,5-1,2.868788,3.090606,2.413939,3.111212
39,IED SAN SALVADOR,5-1,2.721875,3.055208,2.562708,3.041667
9,IED DSLLO DEL TALENTO HUMANO,5-3,2.833929,3.001429,2.488214,3.345357
31,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-B,2.455455,2.969545,2.530909,3.061364
36,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-D,2.826296,2.962963,2.900741,3.307407
8,IED DSLLO DEL TALENTO HUMANO,5-2,2.988519,2.962593,2.691481,3.111852
3,IED BOSTON - SD PPAL,5-1,2.840789,2.894474,2.684737,2.973947
0,IECD MANUEL ELKIN PATARROYO,5-A,2.716809,2.886383,2.623830,3.042553
17,IED JOSE CONSUEGRA HIGGINS,5-3,2.541875,2.875625,2.478750,3.021250
53,IED VILLAS DE SAN PABLO - SEDE PPAL,5-5,2.771562,2.864063,2.563438,3.270938
27,IED MUNDO BOLIVARIANO - SEDE PPAL,5-2,2.920952,2.856667,2.206190,2.778571
26,IED MUNDO BOLIVARIANO - SEDE PPAL,5-1,2.857619,2.842381,2.873333,3.254286
54,IED VILLAS DE SAN PABLO - SEDE PPAL,5-6,2.891935,2.827742,2.505806,3.096774
49,IED VILLAS DE SAN PABLO - SEDE PPAL,5-1,3.052895,2.815263,2.640263,3.035263
16,IED JOSE CONSUEGRA HIGGINS,5-2,2.848182,2.789091,2.332727,2.818182
34,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-B,2.803182,2.787727,3.075909,3.378636
15,IED JOSE CONSUEGRA HIGGINS,5-1,3.136364,2.773182,2.636818,3.243182
55,IIED EL CORAZON DEL SANTUARIO,5-1,2.499583,2.722083,2.402917,3.375417
28,IED MUNDO BOLIVARIANO - SEDE PPAL,5-3,2.752963,2.704444,2.455926,3.036296
1,IECD MANUEL ELKIN PATARROYO,5-B,2.390000,2.672453,2.496038,2.874906
35,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-C,2.754737,2.648947,2.632105,2.998947
38,IED SALVADOR ENTREGAS - SEDE PPAL,5-2,3.062973,2.648649,2.567838,2.937027
29,IED MUNDO BOLIVARIANO - SEDE PPAL,5-4,2.594286,2.642857,2.952857,2.713571
50,IED VILLAS DE SAN PABLO - SEDE PPAL,5-2,2.574828,2.620690,2.552069,2.712069
25,IED LUIS CARLOS GALAN SARMIENTO,5-C,2.598667,2.600667,2.222000,2.754667
20,IED JUAN JOSE RONDON - SEDE PPAL,5-2,2.798500,2.599500,2.349500,2.883500
56,IIED EL CORAZON DEL SANTUARIO,5-2,2.736316,2.596842,2.456316,2.718947
21,IED LOS LAURELES,5-A,2.943143,2.571143,2.733143,3.199143
46,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-4,2.777917,2.542083,2.167500,2.917917
24,IED LUIS CARLOS GALAN SARMIENTO,5-B,2.436429,2.539762,2.523333,2.722381
51,IED VILLAS DE SAN PABLO - SEDE PPAL,5-3,2.500000,2.520294,2.265000,2.891471
2,IECD MANUEL ELKIN PATARROYO,5-C,2.527917,2.514583,2.443750,2.819583
52,IED VILLAS DE SAN PABLO - SEDE PPAL,5-4,2.373333,2.473939,2.282424,2.676364
18,IED JOSE CONSUEGRA HIGGINS,5-4,2.142857,2.460000,2.349524,2.810000
22,IED LOS LAURELES,5-B,2.476286,2.457714,2.303714,3.019143
30,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-A,2.216000,2.451000,2.499500,2.833500
11,IED ETNOEDU PAULINO SALGADO BATATA,5-1,2.603810,2.397619,2.381905,2.952381
33,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-A,2.304348,2.376957,2.275217,2.465217
23,IED LUIS CARLOS GALAN SARMIENTO,5-A,2.466176,2.367794,2.372206,2.750147
47,IED VILLANUEVA SD PPAL,5-A,2.610833,2.165833,1.360000,2.500000
13,IED GOLDA MEIR - SEDE PPAL,5-A,1.490000,1.544667,1.799667,1.955667
48,IED VILLANUEVA SD PPAL,5-B,2.208750,1.458125,1.521875,1.979375
41,IED SANTA MARIA - SD PPAL,5-B,1.333443,1.398689,1.333279,1.639836
10,IED DSLLO DEL TALENTO HUMANO,5-A,2.330000,1.330000,1.670000,2.670000
40,IED SANTA MARIA - SD PPAL,5-A,1.474697,1.328939,1.263182,1.555455
42,IED SANTA MARIA - SD PPAL,5-C,1.384000,1.200500,1.434000,1.532500
14,IED GOLDA MEIR - SEDE PPAL,5-B,1.523214,1.119286,1.095000,1.772500

In [44]:
Medias_curso.sort_values(by="CIENCIAS NATURALES", ascending=False)
## En ciencias sociales es la IED DE CARRIZAL

,Institución,Curso,MATEMÁTICAS,CIENCIAS SOCIALES,CIENCIAS NATURALES,LENGUAJE
6,IED DE CARRIZAL - PPAL,5-C,2.940435,4.144348,3.434783,3.928696
44,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-2,3.193158,3.156316,3.211053,3.350000
32,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-C,2.947895,3.333684,3.209474,3.262105
19,IED JUAN JOSE RONDON - SEDE PPAL,5-1,3.364091,3.287727,3.121364,3.590000
34,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-B,2.803182,2.787727,3.075909,3.378636
43,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-1,3.071071,3.214286,2.976429,3.369286
4,IED DE CARRIZAL - PPAL,5-A,2.968636,3.636818,2.954091,3.515455
29,IED MUNDO BOLIVARIANO - SEDE PPAL,5-4,2.594286,2.642857,2.952857,2.713571
45,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-3,3.182273,3.317727,2.940000,3.621364
36,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-D,2.826296,2.962963,2.900741,3.307407
26,IED MUNDO BOLIVARIANO - SEDE PPAL,5-1,2.857619,2.842381,2.873333,3.254286
7,IED DSLLO DEL TALENTO HUMANO,5-1,3.244000,3.233667,2.855333,3.344000
21,IED LOS LAURELES,5-A,2.943143,2.571143,2.733143,3.199143
8,IED DSLLO DEL TALENTO HUMANO,5-2,2.988519,2.962593,2.691481,3.111852
3,IED BOSTON - SD PPAL,5-1,2.840789,2.894474,2.684737,2.973947
49,IED VILLAS DE SAN PABLO - SEDE PPAL,5-1,3.052895,2.815263,2.640263,3.035263
15,IED JOSE CONSUEGRA HIGGINS,5-1,3.136364,2.773182,2.636818,3.243182
35,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-C,2.754737,2.648947,2.632105,2.998947
0,IECD MANUEL ELKIN PATARROYO,5-A,2.716809,2.886383,2.623830,3.042553
38,IED SALVADOR ENTREGAS - SEDE PPAL,5-2,3.062973,2.648649,2.567838,2.937027
53,IED VILLAS DE SAN PABLO - SEDE PPAL,5-5,2.771562,2.864063,2.563438,3.270938
39,IED SAN SALVADOR,5-1,2.721875,3.055208,2.562708,3.041667
50,IED VILLAS DE SAN PABLO - SEDE PPAL,5-2,2.574828,2.620690,2.552069,2.712069
31,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-B,2.455455,2.969545,2.530909,3.061364
24,IED LUIS CARLOS GALAN SARMIENTO,5-B,2.436429,2.539762,2.523333,2.722381
5,IED DE CARRIZAL - PPAL,5-B,2.754211,3.158421,2.508947,3.526842
54,IED VILLAS DE SAN PABLO - SEDE PPAL,5-6,2.891935,2.827742,2.505806,3.096774
30,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-A,2.216000,2.451000,2.499500,2.833500
1,IECD MANUEL ELKIN PATARROYO,5-B,2.390000,2.672453,2.496038,2.874906
9,IED DSLLO DEL TALENTO HUMANO,5-3,2.833929,3.001429,2.488214,3.345357
17,IED JOSE CONSUEGRA HIGGINS,5-3,2.541875,2.875625,2.478750,3.021250
12,IED ETNOEDU PAULINO SALGADO BATATA,5-2,2.534000,3.288667,2.467333,3.090000
56,IIED EL CORAZON DEL SANTUARIO,5-2,2.736316,2.596842,2.456316,2.718947
28,IED MUNDO BOLIVARIANO - SEDE PPAL,5-3,2.752963,2.704444,2.455926,3.036296
2,IECD MANUEL ELKIN PATARROYO,5-C,2.527917,2.514583,2.443750,2.819583
37,IED SALVADOR ENTREGAS - SEDE PPAL,5-1,2.868788,3.090606,2.413939,3.111212
55,IIED EL CORAZON DEL SANTUARIO,5-1,2.499583,2.722083,2.402917,3.375417
11,IED ETNOEDU PAULINO SALGADO BATATA,5-1,2.603810,2.397619,2.381905,2.952381
23,IED LUIS CARLOS GALAN SARMIENTO,5-A,2.466176,2.367794,2.372206,2.750147
18,IED JOSE CONSUEGRA HIGGINS,5-4,2.142857,2.460000,2.349524,2.810000
20,IED JUAN JOSE RONDON - SEDE PPAL,5-2,2.798500,2.599500,2.349500,2.883500
16,IED JOSE CONSUEGRA HIGGINS,5-2,2.848182,2.789091,2.332727,2.818182
22,IED LOS LAURELES,5-B,2.476286,2.457714,2.303714,3.019143
52,IED VILLAS DE SAN PABLO - SEDE PPAL,5-4,2.373333,2.473939,2.282424,2.676364
33,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-A,2.304348,2.376957,2.275217,2.465217
51,IED VILLAS DE SAN PABLO - SEDE PPAL,5-3,2.500000,2.520294,2.265000,2.891471
25,IED LUIS CARLOS GALAN SARMIENTO,5-C,2.598667,2.600667,2.222000,2.754667
27,IED MUNDO BOLIVARIANO - SEDE PPAL,5-2,2.920952,2.856667,2.206190,2.778571
46,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-4,2.777917,2.542083,2.167500,2.917917
13,IED GOLDA MEIR - SEDE PPAL,5-A,1.490000,1.544667,1.799667,1.955667
10,IED DSLLO DEL TALENTO HUMANO,5-A,2.330000,1.330000,1.670000,2.670000
48,IED VILLANUEVA SD PPAL,5-B,2.208750,1.458125,1.521875,1.979375
42,IED SANTA MARIA - SD PPAL,5-C,1.384000,1.200500,1.434000,1.532500
47,IED VILLANUEVA SD PPAL,5-A,2.610833,2.165833,1.360000,2.500000
41,IED SANTA MARIA - SD PPAL,5-B,1.333443,1.398689,1.333279,1.639836
40,IED SANTA MARIA - SD PPAL,5-A,1.474697,1.328939,1.263182,1.555455
14,IED GOLDA MEIR - SEDE PPAL,5-B,1.523214,1.119286,1.095000,1.772500

In [45]:
Medias_curso.sort_values(by="LENGUAJE", ascending=False)
## En ciencias sociales es la IED DE CARRIZAL

,Institución,Curso,MATEMÁTICAS,CIENCIAS SOCIALES,CIENCIAS NATURALES,LENGUAJE
6,IED DE CARRIZAL - PPAL,5-C,2.940435,4.144348,3.434783,3.928696
45,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-3,3.182273,3.317727,2.940000,3.621364
19,IED JUAN JOSE RONDON - SEDE PPAL,5-1,3.364091,3.287727,3.121364,3.590000
5,IED DE CARRIZAL - PPAL,5-B,2.754211,3.158421,2.508947,3.526842
4,IED DE CARRIZAL - PPAL,5-A,2.968636,3.636818,2.954091,3.515455
34,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-B,2.803182,2.787727,3.075909,3.378636
55,IIED EL CORAZON DEL SANTUARIO,5-1,2.499583,2.722083,2.402917,3.375417
43,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-1,3.071071,3.214286,2.976429,3.369286
44,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-2,3.193158,3.156316,3.211053,3.350000
9,IED DSLLO DEL TALENTO HUMANO,5-3,2.833929,3.001429,2.488214,3.345357
7,IED DSLLO DEL TALENTO HUMANO,5-1,3.244000,3.233667,2.855333,3.344000
36,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-D,2.826296,2.962963,2.900741,3.307407
53,IED VILLAS DE SAN PABLO - SEDE PPAL,5-5,2.771562,2.864063,2.563438,3.270938
32,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-C,2.947895,3.333684,3.209474,3.262105
26,IED MUNDO BOLIVARIANO - SEDE PPAL,5-1,2.857619,2.842381,2.873333,3.254286
15,IED JOSE CONSUEGRA HIGGINS,5-1,3.136364,2.773182,2.636818,3.243182
21,IED LOS LAURELES,5-A,2.943143,2.571143,2.733143,3.199143
8,IED DSLLO DEL TALENTO HUMANO,5-2,2.988519,2.962593,2.691481,3.111852
37,IED SALVADOR ENTREGAS - SEDE PPAL,5-1,2.868788,3.090606,2.413939,3.111212
54,IED VILLAS DE SAN PABLO - SEDE PPAL,5-6,2.891935,2.827742,2.505806,3.096774
12,IED ETNOEDU PAULINO SALGADO BATATA,5-2,2.534000,3.288667,2.467333,3.090000
31,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-B,2.455455,2.969545,2.530909,3.061364
0,IECD MANUEL ELKIN PATARROYO,5-A,2.716809,2.886383,2.623830,3.042553
39,IED SAN SALVADOR,5-1,2.721875,3.055208,2.562708,3.041667
28,IED MUNDO BOLIVARIANO - SEDE PPAL,5-3,2.752963,2.704444,2.455926,3.036296
49,IED VILLAS DE SAN PABLO - SEDE PPAL,5-1,3.052895,2.815263,2.640263,3.035263
17,IED JOSE CONSUEGRA HIGGINS,5-3,2.541875,2.875625,2.478750,3.021250
22,IED LOS LAURELES,5-B,2.476286,2.457714,2.303714,3.019143
35,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-C,2.754737,2.648947,2.632105,2.998947
3,IED BOSTON - SD PPAL,5-1,2.840789,2.894474,2.684737,2.973947
11,IED ETNOEDU PAULINO SALGADO BATATA,5-1,2.603810,2.397619,2.381905,2.952381
38,IED SALVADOR ENTREGAS - SEDE PPAL,5-2,3.062973,2.648649,2.567838,2.937027
46,IED TEC METROPOLITANO DE BARRANQUILLA PARQUE E...,5-4,2.777917,2.542083,2.167500,2.917917
51,IED VILLAS DE SAN PABLO - SEDE PPAL,5-3,2.500000,2.520294,2.265000,2.891471
20,IED JUAN JOSE RONDON - SEDE PPAL,5-2,2.798500,2.599500,2.349500,2.883500
1,IECD MANUEL ELKIN PATARROYO,5-B,2.390000,2.672453,2.496038,2.874906
30,IED NUESTRA SEÑORA DE LAS NIEVES - PPAL,5-A,2.216000,2.451000,2.499500,2.833500
2,IECD MANUEL ELKIN PATARROYO,5-C,2.527917,2.514583,2.443750,2.819583
16,IED JOSE CONSUEGRA HIGGINS,5-2,2.848182,2.789091,2.332727,2.818182
18,IED JOSE CONSUEGRA HIGGINS,5-4,2.142857,2.460000,2.349524,2.810000
27,IED MUNDO BOLIVARIANO - SEDE PPAL,5-2,2.920952,2.856667,2.206190,2.778571
25,IED LUIS CARLOS GALAN SARMIENTO,5-C,2.598667,2.600667,2.222000,2.754667
23,IED LUIS CARLOS GALAN SARMIENTO,5-A,2.466176,2.367794,2.372206,2.750147
24,IED LUIS CARLOS GALAN SARMIENTO,5-B,2.436429,2.539762,2.523333,2.722381
56,IIED EL CORAZON DEL SANTUARIO,5-2,2.736316,2.596842,2.456316,2.718947
29,IED MUNDO BOLIVARIANO - SEDE PPAL,5-4,2.594286,2.642857,2.952857,2.713571
50,IED VILLAS DE SAN PABLO - SEDE PPAL,5-2,2.574828,2.620690,2.552069,2.712069
52,IED VILLAS DE SAN PABLO - SEDE PPAL,5-4,2.373333,2.473939,2.282424,2.676364
10,IED DSLLO DEL TALENTO HUMANO,5-A,2.330000,1.330000,1.670000,2.670000
47,IED VILLANUEVA SD PPAL,5-A,2.610833,2.165833,1.360000,2.500000
33,IED PARA EL DESARROLLO HUMANO MARIA CANO - PPAL,5-A,2.304348,2.376957,2.275217,2.465217
48,IED VILLANUEVA SD PPAL,5-B,2.208750,1.458125,1.521875,1.979375
13,IED GOLDA MEIR - SEDE PPAL,5-A,1.490000,1.544667,1.799667,1.955667
14,IED GOLDA MEIR - SEDE PPAL,5-B,1.523214,1.119286,1.095000,1.772500
41,IED SANTA MARIA - SD PPAL,5-B,1.333443,1.398689,1.333279,1.639836
40,IED SANTA MARIA - SD PPAL,5-A,1.474697,1.328939,1.263182,1.555455
42,IED SANTA MARIA - SD PPAL,5-C,1.384000,1.200500,1.434000,1.532500